<a href="https://colab.research.google.com/github/nanegue/OPA-bot-trading/blob/ml_branch/ml_btc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import libraries
import pandas as pd
import psycopg2 # connexion bdd
# machine learning
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_absolute_error, r2_score, accuracy_score
from sklearn.preprocessing import StandardScaler

IMPORT DES DONNEES A PARTIR DE LA BASE

In [2]:
# Example: 'postgresql://username:password@localhost:5432/your_database'
conn_string = 'postgresql://opauser:opadatapwd@ec2-13-49-68-72.eu-north-1.compute.amazonaws.com:5432/opadb'

# Connexion avec psycopg2
conn = psycopg2.connect(conn_string)

# Open a cursor to perform database operations
cursor = conn.cursor()
print('curseur connecte')

curseur connecte


In [3]:
# notre requête
query = "SELECT * FROM historical_klines WHERE timestamp <= '2024-06-22' ORDER BY timestamp ASC"

# récupération des données
data = pd.read_sql_query(query, conn)
data.head(15)

<ipython-input-3-584fb3f32992>:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql_query(query, conn)


symbol           timestamp     open     high      low    close  \
0   BTCUSDT 2017-08-17 04:00:00  4261.48  4313.62  4261.32  4308.83   
1   ETHUSDT 2017-08-17 04:00:00   301.13   302.57   298.00   301.61   
2   ETHUSDT 2017-08-17 05:00:00   301.61   303.28   300.00   303.10   
3   BTCUSDT 2017-08-17 05:00:00  4308.83  4328.69  4291.37  4315.32   
4   BTCUSDT 2017-08-17 06:00:00  4330.29  4345.45  4309.37  4324.35   
5   ETHUSDT 2017-08-17 06:00:00   302.40   304.44   301.90   302.68   
6   ETHUSDT 2017-08-17 07:00:00   302.68   307.96   302.60   307.96   
7   BTCUSDT 2017-08-17 07:00:00  4316.62  4349.99  4287.41  4349.99   
8   BTCUSDT 2017-08-17 08:00:00  4333.32  4377.85  4333.32  4360.69   
9   ETHUSDT 2017-08-17 08:00:00   307.95   309.97   307.00   308.62   
10  ETHUSDT 2017-08-17 09:00:00   308.62   312.00   308.62   310.00   
11  BTCUSDT 2017-08-17 09:00:00  4360.00  4445.78  4360.00  4444.00   
12  BTCUSDT 2017-08-17 10:00:00  4441.10  4470.00  4399.81  4460.00   
13  ETHUSDT 2017-08-17 10:00:00   310.00   310.97   308.54   309.30   
14  ETHUSDT 2017-08-17 11:00:00   308.30   310.68   307.78   308.95   

        volume  trades  
0    47.181009     171  
1   125.668770     129  
2   377.672460     202  
3    23.234916     102  
4     7.229691      36  
5   303.866720     182  
6   754.745100     198  
7     4.443249      25  
8     0.972807      28  
9   150.750290     182  
10  469.278790     198  
11   10.763623      43  
12   24.865399      82  
13  284.391400     198  
14  273.290400     197

In [4]:
# transformation du temps en index
data = data.set_index(data["timestamp"])
del data["timestamp"] # suppression de la colonne timestamp

In [5]:
# séparation des données des differents crypto dans les df différents
btc = data[data["symbol"] == "BTCUSDT"]
eth = data[data["symbol"] == "ETHUSDT"]
bnb = data[data["symbol"] == "BNBUSDT"]
sol = data[data["symbol"] == "SOLUSDT"]
xrp = data[data["symbol"] == "XRPUSDT"]

# suppression de la colonne 'symbol'
del btc["symbol"]
del eth["symbol"]
del bnb["symbol"]
del sol["symbol"]
del xrp["symbol"]

APERCU DU CONTENU DES DF DES CRYPTO

In [6]:
btc.head(5)

open     high      low    close     volume  trades
timestamp                                                                 
2017-08-17 04:00:00  4261.48  4313.62  4261.32  4308.83  47.181009     171
2017-08-17 05:00:00  4308.83  4328.69  4291.37  4315.32  23.234916     102
2017-08-17 06:00:00  4330.29  4345.45  4309.37  4324.35   7.229691      36
2017-08-17 07:00:00  4316.62  4349.99  4287.41  4349.99   4.443249      25
2017-08-17 08:00:00  4333.32  4377.85  4333.32  4360.69   0.972807      28

In [7]:
eth.head(5)

open    high    low   close     volume  trades
timestamp                                                            
2017-08-17 04:00:00  301.13  302.57  298.0  301.61  125.66877     129
2017-08-17 05:00:00  301.61  303.28  300.0  303.10  377.67246     202
2017-08-17 06:00:00  302.40  304.44  301.9  302.68  303.86672     182
2017-08-17 07:00:00  302.68  307.96  302.6  307.96  754.74510     198
2017-08-17 08:00:00  307.95  309.97  307.0  308.62  150.75029     182

CREATION DES MODELES DE ML ET ENTRAINEMENT
LA VARIABLE A PREDIRE EST LE PRIX DE CLOTURE DE LA CRYPTO POUR LA PROCHAINE BOUGIE HORAIRE(POUR LES MODELES LINEAIRES) ET HAUSSE/BAISSE DU PRIX DE CLOTURE DE LA CRYPTO( CAS DES ML DE CLASSIFICATION)


In [8]:
# Création des colonnes target qu'on predira pour les 2 types de ML
btc["in_1_hour"] = btc["close"].shift(-1)   # variable target correspond au prix de la crypto dans 1 h
btc["price_change"] = btc["in_1_hour"] - btc["close"]
btc["price_up"] = (btc["price_change"] > 0).astype(int) # 1 si on prédit une hausse, 0 si une baisse
# on supprime la dernière ligne car il n'y a de valeur pour btc["close"].shift(-1)
btc = btc[:-1]

<ipython-input-8-e287e0c4a5bf>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  btc["in_1_hour"] = btc["close"].shift(-1)   # variable target correspond au prix de la crypto dans 1 h
<ipython-input-8-e287e0c4a5bf>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  btc["price_change"] = btc["in_1_hour"] - btc["close"]
<ipython-input-8-e287e0c4a5bf>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the cave

In [9]:
btc.head(5)

open     high      low    close     volume  trades  \
timestamp                                                                    
2017-08-17 04:00:00  4261.48  4313.62  4261.32  4308.83  47.181009     171   
2017-08-17 05:00:00  4308.83  4328.69  4291.37  4315.32  23.234916     102   
2017-08-17 06:00:00  4330.29  4345.45  4309.37  4324.35   7.229691      36   
2017-08-17 07:00:00  4316.62  4349.99  4287.41  4349.99   4.443249      25   
2017-08-17 08:00:00  4333.32  4377.85  4333.32  4360.69   0.972807      28   

                     in_1_hour  price_change  price_up  
timestamp                                               
2017-08-17 04:00:00    4315.32          6.49         1  
2017-08-17 05:00:00    4324.35          9.03         1  
2017-08-17 06:00:00    4349.99         25.64         1  
2017-08-17 07:00:00    4360.69         10.70         1  
2017-08-17 08:00:00    4444.00         83.31         1

In [10]:
# divisions des données en variable 'features' et  variable 'target"
feats = btc[['open', 'high', 'low', 'close', 'volume', 'trades']]
target_reg = btc["in_1_hour"]
target_clf = btc["price_up"]

In [11]:
feats.head(5)

open     high      low    close     volume  trades
timestamp                                                                 
2017-08-17 04:00:00  4261.48  4313.62  4261.32  4308.83  47.181009     171
2017-08-17 05:00:00  4308.83  4328.69  4291.37  4315.32  23.234916     102
2017-08-17 06:00:00  4330.29  4345.45  4309.37  4324.35   7.229691      36
2017-08-17 07:00:00  4316.62  4349.99  4287.41  4349.99   4.443249      25
2017-08-17 08:00:00  4333.32  4377.85  4333.32  4360.69   0.972807      28

In [13]:
target_reg.head(5)

timestamp
2017-08-17 04:00:00    4315.32
2017-08-17 05:00:00    4324.35
2017-08-17 06:00:00    4349.99
2017-08-17 07:00:00    4360.69
2017-08-17 08:00:00    4444.00
Name: in_1_hour, dtype: float64

In [14]:
target_clf.head(5)

timestamp
2017-08-17 04:00:00    1
2017-08-17 05:00:00    1
2017-08-17 06:00:00    1
2017-08-17 07:00:00    1
2017-08-17 08:00:00    1
Name: price_up, dtype: int64

In [15]:
# on sépare les données en se basant sur  une date
train_date, test_date = "2023-12-30", "2024-01-01"
# donnees de "train" vont  de la date la plus ancienne jusqu 'au "2023-12-30"
#donnees de "test" commence "2024-01-01" jusqu'a la date la plus recente des donnees extraites

X_train, X_test = feats.loc[:train_date], feats[test_date:]
y_reg_train, y_reg_test = target_reg[:train_date], target_reg[test_date:]
y_clf_train, y_clf_test = target_clf[:train_date], target_clf[test_date:]

In [16]:
# Normalisation des caractéristiques
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
# Entrainement des modèles de regression
rf_regressor = RandomForestRegressor()
gb_regressor = GradientBoostingRegressor()
lr_regressor = LinearRegression()

rf_regressor.fit(X_train_scaled, y_reg_train)
gb_regressor.fit(X_train_scaled, y_reg_train)
lr_regressor.fit(X_train_scaled, y_reg_train)

LinearRegression()

In [ ]:
# Entrainement des modèles de classification
rf_classifier = RandomForestClassifier()
gb_classifier = GradientBoostingClassifier()
lr_classifier = LogisticRegression()

rf_classifier.fit(X_train_scaled, y_clf_train)
gb_classifier.fit(X_train_scaled, y_clf_train)
lr_classifier.fit(X_train_scaled, y_clf_train)

UTILISATION DE MLFLOW POUR ENTRAINER NOS MODELES

In [20]:
pip install mlflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 31.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.4/233.4 kB 23.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 18.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 22.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 kB 16.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 kB 6.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.0/107.0 kB 13.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.4/84.4 kB 10.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 kB 9.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 7.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.9/202.9 kB 24.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 kB 7.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━

ENTRAINEMENT DES 3 MODELES DE REGRESSION VIA MLFLOW

In [22]:
import mlflow
# definir une exprience globale , si on ne definit pas , mlfow va le placer dans un dossie par defaut
mlflow.set_experiment("Regression_models")   # permet de definir une experience nomme Regression_models" pour essaye les modeles de regression
mlflow.sklearn.autolog()  # appelle l api sklearn de mlflow qui integre tous les algo de scikitlearn
print('creation dune experience nomme Regression_models" dans MLFLOW pour entrainer les modeles de regression')

2024/06/25 21:32:51 INFO mlflow.tracking.fluent: Experiment with name 'Regression_models' does not exist. Creating a new experiment.


creation dune experience nomme Regression_models" dans MLFLOW pour entrainer les modeles de regression


In [31]:

# premier run modele de regression
print('creer notre execution (run) pour le modele random forest regressor')
with mlflow.start_run(run_name="RandomForestReg"):   # creer notre execution (run) pour le modele random forest regressor
  # code classique de creation d un modele de ML
  rf_regressor = RandomForestRegressor()
  rf_regressor.fit(X_train_scaled, y_reg_train.to_numpy())


creer notre execution (run) pour le modele random forest regressor


In [35]:
# second  run
with mlflow.start_run(run_name="GradientBoostingReg"):   # creer notre execution (run) pour le modele GradientBoostingRegressor
  # code classique de creation d un modele de ML
  gb_regressor = GradientBoostingRegressor()
  #gb_regressor.fit(X_train_scaled, y_reg_train)
  # ajout de .numpy() pour eviter Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'
  gb_regressor.fit(X_train_scaled, y_reg_train.to_numpy())

In [37]:
# troisieme  run
with mlflow.start_run(run_name="LinearReg"):   # creer notre execution (run) pour le modele LinearRegression
  # code classique de creation d un modele de ML
  lr_regressor = LinearRegression()
  lr_regressor.fit(X_train_scaled, y_reg_train.to_numpy())

PREDICTIONS EN UTILISANT LE CODE GENERE SUITE AU RUN MLFLOW

In [46]:
# pour le modele LinearRegression

import mlflow
logged_model = 'runs:/60306ee9a6c540b8b6bfaa45659e53a4/model' # id d un run du modele linearRegression dans MLflow

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.
import pandas as pd
predict_linear_reg = loaded_model.predict(X_test_scaled)


In [41]:
predict_linear_reg

array([42472.19264137, 42616.61820672, 42569.31528971, ...,
       64061.09659765, 64139.77430939, 64127.28489282])

In [42]:
# pour le modele GradientBoostingRegressor

logged_model = 'runs:/fdd84b05c18243b6b9c7a7b0a9f42aac/model'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.
import pandas as pd
predict_Grad_boost_reg =  loaded_model.predict(X_test_scaled)

predict_Grad_boost_reg

array([42165.54321195, 42893.00271939, 42893.00271939, ...,
       64193.25103971, 64193.25103971, 64226.31619629])

In [44]:
# pour le modele RandomForestRegressor
logged_model = 'runs:/473b676a9eb04e45912190cc56381b46/model'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.
import pandas as pd
predict_Randon_forest_reg =  loaded_model.predict(X_test_scaled)
predict_Randon_forest_reg

array([42494.2758, 42541.4777, 42540.3414, ..., 64158.7746, 64324.5933,
       64351.5557])

In [45]:
y_reg_test

timestamp
2024-01-01 00:00:00    42613.56
2024-01-01 01:00:00    42581.10
2024-01-01 02:00:00    42330.49
2024-01-01 03:00:00    42399.99
2024-01-01 04:00:00    42234.01
                         ...   
2024-06-21 19:00:00    64200.52
2024-06-21 20:00:00    64084.43
2024-06-21 21:00:00    64155.02
2024-06-21 22:00:00    64143.56
2024-06-21 23:00:00    64056.47
Name: in_1_hour, Length: 4152, dtype: float64

In [47]:
# creation d un autre experiment sur MLFLOW pour l entrainement des modeles de classification

mlflow.set_experiment("Classification_models")   # permet de definir une experience nomme Classification_models" pour essaye les modeles de classification
mlflow.sklearn.autolog()  # appelle l api sklearn de mlflow qui integre tous les algo de scikitlearn
print('creation dune experience nomme Classification_models" dans MLFLOW pour entrainer les modeles de classification')

2024/06/25 22:18:15 INFO mlflow.tracking.fluent: Experiment with name 'Classification_models' does not exist. Creating a new experiment.


creation dune experience nomme Classification_models" dans MLFLOW pour entrainer les modeles de classification


In [48]:
# premier run modele de classification
print('creer notre execution (run) pour le modele RandomForestClassifier')
with mlflow.start_run(run_name="RandomForestClassifier"):   # creer notre execution (run) pour le modele RandomForestClassifier
  # code classique de creation d un modele de ML
  rf_classifier = RandomForestClassifier()
  rf_classifier.fit(X_train_scaled, y_clf_train.to_numpy())

creer notre execution (run) pour le modele RandomForestClassifier


In [49]:
# second run modele de classification
print('creer notre execution (run) pour le modele GradientBoostingClassifier')
with mlflow.start_run(run_name="GradientBoostingClassifier"):   # creer notre execution (run) pour le modele GradientBoostingClassifier
  # code classique de creation d un modele de ML
  gb_classifier = GradientBoostingClassifier()
  gb_classifier.fit(X_train_scaled, y_clf_train.to_numpy())


creer notre execution (run) pour le modele GradientBoostingClassifier


In [50]:
# troisieme run modele de classification
print('creer notre execution (run) pour le modele LogisticRegression')
with mlflow.start_run(run_name="LogisticRegression"):   # creer notre execution (run) pour le modele LogisticRegression
  # code classique de creation d un modele de ML
  lr_classifier = LogisticRegression()
  lr_classifier.fit(X_train_scaled, y_clf_train.to_numpy())

creer notre execution (run) pour le modele LogisticRegression


PREDICTIONS POUR LES MODELES DE CLASSIFICATION VIA CODE FOURNI PAR MLFLOW

In [53]:
# pour le modele LogistiRegression

logged_model = 'runs:/64065da967794f15a76570277b88052e/model'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.

predict_logitic_reg = loaded_model.predict(X_test_scaled)

In [54]:
predict_logitic_reg

array([0, 0, 0, ..., 0, 0, 0])

In [55]:
# pour le modele GradientBoostingClassifier
logged_model = 'runs:/b807a57ea95e421684275c758ceecb23/model'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.

predict_grad_boost_classifier = loaded_model.predict(X_test_scaled)

In [56]:
predict_grad_boost_classifier

array([1, 1, 1, ..., 0, 1, 1])

In [57]:
# pour le modele RandomForestClassifier
logged_model = 'runs:/87775ea692ae444a831e8a1fbbfebce0/model'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.

predict_rand_forest_classifier = loaded_model.predict(X_test_scaled)

In [58]:
predict_rand_forest_classifier

array([1, 0, 0, ..., 1, 1, 1])

In [59]:
y_clf_test

timestamp
2024-01-01 00:00:00    1
2024-01-01 01:00:00    0
2024-01-01 02:00:00    0
2024-01-01 03:00:00    1
2024-01-01 04:00:00    0
                      ..
2024-06-21 19:00:00    0
2024-06-21 20:00:00    0
2024-06-21 21:00:00    1
2024-06-21 22:00:00    0
2024-06-21 23:00:00    0
Name: price_up, Length: 4152, dtype: int64

In [60]:
import joblib

# Enregistrer le scaler avec joblib
joblib.dump(scaler, "models/btc_scaler")


FileNotFoundError: [Errno 2] No such file or directory: 'models/btc_scaler'

In [ ]:
# Enregistrement du modèle avec joblib
joblib.dump(gb_regressor, "models/btc_gb_regressor_model")

INSTALLATION DE NGROK POUR PERMETTRE DE VISUALISER L'INTERFACE DE MLFLOW


In [28]:
pip install pyngrok

In [51]:
# ce script doit être execute pour voir dans linterface graghique de mlflow le resultat de nos runs

from pyngrok import ngrok
# Terminate open tunnels if exist
ngrok.kill()

# Setting the authtoken (optional)
# Get your authtoken from https://dashboard.ngrok.com/auth
NGROK_AUTH_TOKEN = "2iN1HgKmdaDkZwtAqk5Cg3BoLKA_4par6tW5kEMAtajnE6A3t"
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Open an HTTPs tunnel on port 5000 for http://localhost:5000
ngrok_tunnel = ngrok.connect(addr="5000", proto="http", bind_tls=True)
print("MLflow Tracking UI:", ngrok_tunnel.public_url)

MLflow Tracking UI: https://09c3-34-125-148-137.ngrok-free.app


In [52]:
!mlflow ui

[2024-06-25 22:30:04 +0000] [27416] [INFO] Starting gunicorn 22.0.0
[2024-06-25 22:30:04 +0000] [27416] [INFO] Listening at: http://127.0.0.1:5000 (27416)
[2024-06-25 22:30:04 +0000] [27416] [INFO] Using worker: sync
[2024-06-25 22:30:04 +0000] [27417] [INFO] Booting worker with pid: 27417
[2024-06-25 22:30:04 +0000] [27421] [INFO] Booting worker with pid: 27421
[2024-06-25 22:30:04 +0000] [27423] [INFO] Booting worker with pid: 27423
[2024-06-25 22:30:05 +0000] [27424] [INFO] Booting worker with pid: 27424


[2024-06-25 22:37:49 +0000] [27416] [INFO] Handling signal: int
[2024-06-25 22:37:49 +0000] [27421] [INFO] Worker exiting (pid: 27421)
[2024-06-25 22:37:49 +0000] [27423] [INFO] Worker exiting (pid: 27423)
[2024-06-25 22:37:49 +0000] [27417] [INFO] Worker exiting (pid: 27417)
[2024-06-25 22:37:49 +0000] [27424] [INFO] Worker exiting (pid: 27424)

Aborted!
[2024-06-25 22:37:51 +0000] [27416] [INFO] Shutting down: Master
